services:
  crypto-collector:
    build: .
    container_name: crypto-collector
    restart: always
    networks:
      - crypto-net


  timescale-db:
    image: timescale/timescaledb:latest-pg16
    container_name: crypto-timescale-db
    restart: always
    user: postgres
    ports:
      - "5460:5432"
    environment:
      POSTGRES_DB: crypto-timescale-db
      POSTGRES_USER: timescale
      POSTGRES_PASSWORD: timescale
    volumes:
      - crypto-timescale-db:/var/lib/postgresql/data
    networks:
      - crypto-net


  grafana:
    image: grafana/grafana
    container_name: crypto-grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - crypto-grafana:/var/lib/grafana
    networks:
      - crypto-net

  prometheus:
    image: prom/prometheus:latest
    container_name: crypto-prometheus
    command:
      --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
    networks:
      - crypto-net




volumes:
  crypto-grafana:
  crypto-timescale-db:


networks:
  crypto-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24