version: "3.8"

services:
  crypto-bot:
    build: .
    container_name: crypto-bot
    restart: always
    depends_on:
      - postgres-db
      - clickhouse
    networks:
      - crypto-net


  postgres-db:
    image: postgres:latest
    container_name: crypto-db
    restart: always
    user: postgres
    ports:
      - "5455:5432"
    environment:
      POSTGRES_DB: crypto-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - crypto-db:/var/lib/postgresql/data/
    networks:
      - crypto-net

#  clickhouse:
#    image: bitnami/clickhouse:latest
#    container_name: crypto-clickhouse
#    restart: always
#    ports:
#      - "127.0.0.1:9000:9000"
#      - "127.0.0.1:8123:8123"
#    volumes:
#      - crypto-clickhouse:/var/lib/clickhouse
#    environment:
#      - CLICKHOUSE_ADMIN_PASSWORD=password
#    networks:
#        - crypto-net

  grafana:
    image: grafana/grafana
    container_name: crypto-grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - crypto-grafana:/var/lib/grafana
    networks:
      - crypto-net

  prometheus:
    image: prom/prometheus:latest
    container_name: crypto-prometheus
    command:
      --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
    networks:
      - crypto-net




volumes:
  crypto-cache:
  crypto-db:
  crypto-clickhouse:
  crypto-grafana:


networks:
  crypto-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24