version: "3.8"

services:
  bot:
    build: .
    container_name: crypto-bot
    restart: always
    depends_on:
      - postgres-db
    networks:
      - crypto-net


  postgres-db:
    image: postgres:latest
    container_name: crypto-db
    restart: always
    user: postgres
    ports:
      - "5455:5432"
    environment:
      POSTGRES_DB: crypto-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - crypto-db:/var/lib/postgresql/data/
    networks:
      - crypto-net

  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "docker"
    networks:
      - crypto-net


volumes:
  crypto-cache:
  crypto-db:


networks:
  crypto-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24